openapi: 3.1.0
info:
  title: Product Search API with Datalist Support
  version: 1.0.0
  description: Demonstrates query parameters that support HTML5 datalist functionality

paths:
  /products:
    get:
      summary: Search products with datalist suggestions
      operationId: searchProducts
      description: |
        This endpoint demonstrates how to document parameters that should
        be rendered with HTML5 datalist suggestions while allowing free text input.
        
        **Frontend Implementation:**
        Use the `examples` array to populate an HTML5 `<datalist>` element:
        ```html
        <input list="category-suggestions" name="category">
        <datalist id="category-suggestions">
          <option value="electronics">
          <option value="clothing">
          <option value="books">
        </datalist>
        ```
      parameters:
        - name: category
          in: query
          description: |
            Product category with datalist suggestions.
            Users can select from suggestions or type custom values.
            
            **HTML5 Implementation:**
            ```html
            <input list="category-datalist" name="category">
            <datalist id="category-datalist">
              <!-- Populate from 'examples' array -->
            </datalist>
            ```
          required: false
          schema:
            type: string
            minLength: 2
            maxLength: 50
            # Pattern allows letters, numbers, spaces, hyphens, and ampersands
            pattern: '^[a-zA-Z0-9\s\-&]+$'
          examples:
            # These values populate the datalist
            electronics:
              summary: Electronics category
              value: electronics
            clothing:
              summary: Clothing and apparel
              value: clothing
            books:
              summary: Books and media
              value: books
            home_garden:
              summary: Home and garden
              value: home & garden
            sports:
              summary: Sports equipment
              value: sports
            automotive:
              summary: Automotive parts
              value: automotive
          # Custom extension for datalist metadata (optional)
          x-datalist:
            autocomplete: true
            showOnFocus: true
            minChars: 1

        - name: sort_by
          in: query
          description: |
            Sort field with datalist suggestions.
            Includes common sort options but accepts custom fields.
          required: false
          schema:
            type: string
            default: relevance
          examples:
            relevance:
              value: relevance
              summary: Sort by relevance (default)
            price_asc:
              value: price
              summary: Sort by price (low to high)
            price_desc:
              value: -price
              summary: Sort by price (high to low)
            newest:
              value: -date
              summary: Sort by newest first
            rating:
              value: -rating
              summary: Sort by highest rating
            name:
              value: name
              summary: Sort alphabetically
          x-datalist-sort: true

        - name: color
          in: query
          description: |
            Filter by color with comprehensive suggestions.
            Uses common color names but accepts any color value.
          required: false
          schema:
            type: string
            # CSS color pattern (supports hex, rgb, named colors)
            pattern: '^(#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})|rgb\(\d{1,3},\s*\d{1,3},\s*\d{1,3}\)|[a-zA-Z\s]+)$'
          examples:
            # Common color names for datalist
            red:
              value: red
            blue:
              value: blue
            green:
              value: green
            black:
              value: black
            white:
              value: white
            gray:
              value: gray
            navy:
              value: navy
            teal:
              value: teal
            purple:
              value: purple
            pink:
              value: pink
            orange:
              value: orange
            yellow:
              value: yellow
            brown:
              value: brown
            beige:
              value: beige
            silver:
              value: silver
            gold:
              value: gold
            # CSS color formats also supported
            hex_red:
              value: "#ff0000"
            rgb_blue:
              value: "rgb(0, 0, 255)"

      responses:
        '200':
          description: Successful product search
          content:
            application/json:
              schema:
                type: object
                properties:
                  products:
                    type: array
                    items:
                      $ref: '#/components/schemas/Product'
                  suggestions:
                    type: object
                    properties:
                      category:
                        type: array
                        items:
                          type: string
                        description: Additional category suggestions based on search
                      similar_searches:
                        type: array
                        items:
                          type: string

  /users/search:
    get:
      summary: Search users with typeahead suggestions
      parameters:
        - name: department
          in: query
          description: |
            Department filter with datalist populated from active departments.
            Suggestions come from commonly used departments.
          schema:
            type: string
          examples:
            engineering:
              value: Engineering
              x-frequency: high
            sales:
              value: Sales
              x-frequency: high
            marketing:
              value: Marketing
              x-frequency: medium
            hr:
              value: Human Resources
              x-frequency: medium
            finance:
              value: Finance
              x-frequency: medium
            it:
              value: IT Support
              x-frequency: low
            legal:
              value: Legal
              x-frequency: low
          x-datalist-source: active-departments

        - name: location
          in: query
          description: |
            Office location with hierarchical suggestions.
            Can use parent-child relationships in datalist.
          schema:
            type: string
          examples:
            # Format: City (Country) for better datalist display
            ny_usa:
              value: "New York (USA)"
              x-region: "North America"
            london_uk:
              value: "London (UK)"
              x-region: "Europe"
            tokyo_jp:
              value: "Tokyo (Japan)"
              x-region: "Asia"
            sydney_au:
              value: "Sydney (Australia)"
              x-region: "Oceania"
            berlin_de:
              value: "Berlin (Germany)"
              x-region: "Europe"
            toronto_ca:
              value: "Toronto (Canada)"
              x-region: "North America"
          x-datalist-grouped: true

components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        category:
          type: string
        price:
          type: number
          format: float
        colors:
          type: array
          items:
            type: string

  # Optional: Define common datalist values as reusable components
  parameters:
    CategoryDatalist:
      name: category
      in: query
      description: Product category with datalist suggestions
      schema:
        type: string
      examples:
        electronics: { value: "electronics" }
        clothing: { value: "clothing" }
        books: { value: "books" }
        home_garden: { value: "home & garden" }

    ColorDatalist:
      name: color
      in: query
      description: Color filter with extensive suggestions
      schema:
        type: string
      examples:
        red: { value: "red" }
        blue: { value: "blue" }
        green: { value: "green" }
        black: { value: "black" }
        white: { value: "white" }

# Datalist implementation guidance
x-datalist-implementation: |
  ## HTML5 Datalist Implementation Guide
  
  For parameters with `examples`, implement as:
  
  ```html
  <!-- Basic datalist -->
  <input type="text" name="{param_name}" list="{param_name}-datalist">
  <datalist id="{param_name}-datalist">
    {% for example in param.examples %}
      <option value="{{ example.value }}">
        {{ example.summary or example.value }}
      </option>
    {% endfor %}
  </datalist>

